if: tag != latest

language: go

go:
  - "1.x"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libgit2-dev
      - libgpm-dev

script:
  - make test && make clean &&
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then make static; fi

